Repository kubevirt/cdi-operator, pull requests merged in 2018-11, with the labels that each got.

#9 Add cdi provision and deprovision to the dockerfile
  Dockerfile
Labels: size/XS

#11 Support cdi-operator deployment through the OLM
  deploy/olm-catalog/catalog-source.yaml
  deploy/olm-catalog/configmap.yaml
Labels: size/L

#13 Fix image build
  Dockerfile
Labels: size/S

#14 Set wider permissions to deploy also from OLM
  Makefile
  deploy/rbac.yaml
Labels: size/S

#15 Add initial README.md
  README.md
Labels: size/S
